name: Docker Deploy (Windows)

on:
  push:
    branches:
      - joseortega   # Cambia esto si tu rama principal es otra

jobs:
  build-and-run:
    runs-on: self-hosted   # Usas tu runner local en Windows
    defaults:
      run:
        shell: powershell

    steps:
      - name: Checkout código
        uses: actions/checkout@v4
        
      - name: Limpiar contenedor previo si existe
        run: |
          docker stop laboratorio-final-devops *>$null; if ($LASTEXITCODE -eq 0) { Write-Output "Contenedor detenido" } else { Write-Output "No estaba corriendo" }
          docker rm laboratorio-final-devops *>$null; if ($LASTEXITCODE -eq 0) { Write-Output "Contenedor eliminado" } else { Write-Output "No existía" }

      - name: Build JAR con Maven
        run: |
          mvn clean package | Tee-Object -FilePath build-log.txt

      - name: Construir imagen Docker
        run: |
          docker build -t laboratorio-final-devops:1.0 . | Tee-Object -FilePath docker-build-log.txt

      - name: Ejecutar contenedor
        run: |
          docker run -d -p 8081:8081 --name laboratorio-final-devops laboratorio-final-devops:1.0 | Tee-Object -FilePath docker-run-log.txt

      - name: Verificar contenedores activos
        run: |
          docker ps -a | Tee-Object -FilePath docker-ps-log.txt

      - name: Esperar a que la app esté lista
        run: |
          Write-Output "Esperando que la aplicación se inicie..." | Tee-Object -FilePath app-ready-log.txt
          Start-Sleep -Seconds 15

      - name: Test automático con curl
        run: |
          Write-Output "Ejecutando prueba automática..." | Tee-Object -FilePath test-log.txt
          Invoke-WebRequest -Uri http://localhost:8081/ -UseBasicParsing
          if ($LASTEXITCODE -ne 0) { exit 1 }

      - name: Subir logs como artefacto
        uses: actions/upload-artifact@v4
        with:
          name: deployment-logs
          path: |
            build-log.txt
            docker-build-log.txt
            docker-run-log.txt
            docker-ps-log.txt
            app-ready-log.txt
            test-log.txt